language: c

before_install:
  - sudo apt-get install realpath software-properties-common 
  - sudo add-apt-repository universe
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install -y -t xenial \
    gcc-mingw-w64-i686 g++-mingw-w64-i686 binutils-mingw-w64-i686
  - apt-get -f install -y \
      build-essential \
      autoconf \
      autogen \
      bison \
      dejagnu \
      flex \
      flip \
      gawk \
      git \
      gperf \
      gzip \
      nsis \
      openssh-client \
      p7zip-full \
      perl \
      python-dev \
      libisl-dev \
      scons \
      tcl \
      texinfo \
      tofrodos \
      wget \
      zip \
      texlive \
      texlive-extra-utils
  - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-src.tar.bz2
  - tar xvf gcc-arm-none-eabi-6-2017-q2-update-src.tar.bz2

script: cd gcc-arm-none-eabi-6-2017-q2-update && ./install-src.sh && ./build-prerequisites.sh && ./build-toolchain.sh
